import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ClerkProvider>
        <body>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
